- 👋 Hi, I’m @ft-Dane
- 👀 I’m interested in Chaecasso...
- 🌱 I’m currently learning Web Developing...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
ft-Dane/ft-Dane is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
